server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/*_access.log
    
    pipeline_stages:
      - json:
      - labels:
          timestamp:
          client_ip:
          request_method:
          request_uri:
          status_code:
          user_agent:
          is_suspicious_agent:
          has_proxy_headers:
          is_aws_service:
          route_decision:
          request_id:
